const { withAppBuildGradle } = require('@expo/config-plugins');

const HELPERS_MARKER = '// @generated by withAndroidLocalSigning';

const SIGNING_HELPERS = `
${HELPERS_MARKER}
def localEasCredentialsJson = rootProject.file("../credentials.json")
def localEasCredentials = localEasCredentialsJson.exists()
    ? new groovy.json.JsonSlurper().parse(localEasCredentialsJson)
    : null

def configureLocalEasReleaseSigning = { signingConfig ->
    if (localEasCredentials == null) {
        return
    }

    def keystorePath = java.nio.file.Paths.get(localEasCredentials.android.keystore.keystorePath)
    def storeFilePath = keystorePath.isAbsolute()
        ? keystorePath
        : rootProject.file("..").toPath().resolve(keystorePath)

    signingConfig.storeFile storeFilePath.toFile()
    signingConfig.storePassword localEasCredentials.android.keystore.keystorePassword
    signingConfig.keyAlias localEasCredentials.android.keystore.keyAlias
    signingConfig.keyPassword localEasCredentials.android.keystore.containsKey("keyPassword")
        ? localEasCredentials.android.keystore.keyPassword
        : localEasCredentials.android.keystore.keystorePassword
}
`;

function insertSigningHelpers(contents) {
  if (contents.includes(HELPERS_MARKER)) return contents;

  // Preserve native projects generated by older versions of this plugin that
  // inserted the helpers before the marker was introduced.
  if (
    contents.includes('def localEasCredentialsJson =') &&
    contents.includes('def configureLocalEasReleaseSigning =')
  ) {
    return contents.replace(
      'def localEasCredentialsJson =',
      `${HELPERS_MARKER}\ndef localEasCredentialsJson =`
    );
  }

  const projectRootLine = 'def projectRoot = rootDir.getAbsoluteFile().getParentFile().getAbsolutePath()';
  if (contents.includes(projectRootLine)) {
    return contents.replace(projectRootLine, `${projectRootLine}\n${SIGNING_HELPERS}`);
  }

  return contents.replace(/\nandroid\s*\{/, `\n${SIGNING_HELPERS}\nandroid {`);
}

function insertReleaseSigningConfig(contents) {
  if (contents.includes('configureLocalEasReleaseSigning(delegate)')) return contents;

  return contents.replace(
    /signingConfigs\s*\{/,
    `signingConfigs {\n        release {\n            configureLocalEasReleaseSigning(delegate)\n        }`
  );
}

function pointReleaseBuildAtReleaseSigning(contents) {
  if (contents.includes('signingConfig localEasCredentials != null ? signingConfigs.release : signingConfigs.debug')) {
    return contents;
  }

  return contents.replace(
    /(release\s*\{[\s\S]*?signingConfig\s+)signingConfigs\.debug/,
    '$1localEasCredentials != null ? signingConfigs.release : signingConfigs.debug'
  );
}

module.exports = function withAndroidLocalSigning(config) {
  return withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;
    contents = insertSigningHelpers(contents);
    contents = insertReleaseSigningConfig(contents);
    contents = pointReleaseBuildAtReleaseSigning(contents);
    config.modResults.contents = contents;
    return config;
  });
};
